title: My New Jekyll Site
author: Your Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: # Keywords describing your site
- jekyll
- forestry.io
- static site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
